project/app/clientes/urls.py
from app.clientes.api import CandidatosEmpresaTemplateView, ClienteTemplateView, ClienteUserViewSet, InvestigacionClienteEmpresaViewSet, InvestigacionClienteViewSet, CandidatosTemplateView
from app.clientes.views.clientes_users import (
    ClienteUserCreateView,
    ClienteUserDetailView,
    ClienteUserUpdatePasswdView,
    ClienteUserUpdateView,
)
from app.clientes.views.pagos import (
    ClientesFacturaDetailView,
    ClientesFacturaTemplateView,
    InvestigacionClienteFacturaViewSet,
    InvestigacionFacturaClienteArchivoCreateView,
    InvestigacionFacturaClienteArchivoUpdateView,
)
from app.clientes.views.solicitudes import (
    ClienteSolicitudCandidatoCreateView,
    ClienteSolicitudCandidatoDeleteView,
    ClienteSolicitudCandidatoUpdateView,
    ClienteSolicitudCreateTemplateView,
    ClienteSolicitudDeleteView,
    ClienteSolicitudDetailView,
    ClienteSolicitudEmpresaListView,
    ClienteSolicitudEnviarTemplateView,
    ClienteSolicitudListView,
    ClienteSolicitudObservacionUpdateView,
    InitialClient,
    MunicipiosView,
    SendEmailApiView,
)
from django.urls import include, path
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r"clientes", ClienteUserViewSet)
router.register(r"clientes_facturas", InvestigacionClienteFacturaViewSet)
router.register(r"candidatos", InvestigacionClienteViewSet)
router.register(r"candidatos_empresa", InvestigacionClienteEmpresaViewSet)

app_name = "clientes"

urlpatterns = [
    path("api/", include(router.urls)),
    path("list/", ClienteTemplateView.as_view(), name="clientes_list"),
    path("user/create/", ClienteUserCreateView.as_view(), name="clientes_users_create"),
    path(
        "user/detail/<int:pk>/",
        ClienteUserDetailView.as_view(),
        name="clientes_users_detail",
    ),
    path(
        "user/update/<int:pk>/",
        ClienteUserUpdateView.as_view(),
        name="clientes_users_update",
    ),
    path(
        "user/password/update/<int:pk>/",
        ClienteUserUpdatePasswdView.as_view(),
        name="clientes_users_password_update",
    ),
    path("", InitialClient.as_view(), name="clientes_initial"),
    path(
        "solicitudes/",
        ClienteSolicitudListView.as_view(),
        name="clientes_solicitudes_list",
    ),
    path(
        "solicitudes/empresa",
        ClienteSolicitudEmpresaListView.as_view(),
        name="clientes_solicitudes_empresa_list",
    ),
    path(
        "solicitudes/create/",
        ClienteSolicitudCreateTemplateView.as_view(),
        name="clientes_solicitudes_create",
    ),
    path(
        "solicitudes/detail/<int:pk>/",
        ClienteSolicitudDetailView.as_view(),
        name="clientes_solicitud_detail",
    ),
    path(
        "solicitudes/observacion_update/<int:pk>/",
        ClienteSolicitudObservacionUpdateView.as_view(),
        name="clientes_solicitud_update_observacion",
    ),
    path(
        "solicitudes/delete/<int:pk>/",
        ClienteSolicitudDeleteView.as_view(),
        name="clientes_solicitud_delete",
    ),
    path(
        "solicitudes/enviar/<int:solicitud_id>/",
        ClienteSolicitudEnviarTemplateView.as_view(),
        name="clientes_solicitud_enviar",
    ),
    path(
        "solicitudes/candidato/create/<int:solicitud_id>/",
        ClienteSolicitudCandidatoCreateView.as_view(),
        name="clientes_solicitud_candidato_create",
    ),
    path(
        "solicitudes/candidato/update/<int:solicitud_id>/<int:pk>",
        ClienteSolicitudCandidatoUpdateView.as_view(),
        name="clientes_solicitud_candidato_update",
    ),
    path(
        "solicitudes/candidato/delete/<int:solicitud_id>/<int:pk>",
        ClienteSolicitudCandidatoDeleteView.as_view(),
        name="clientes_solicitud_candidato_delete",
    ),
    path(
        "solicitudes/solicitud/enviar/email/",
        SendEmailApiView.as_view(),
        name="clientes_solicitud_enviar_email",
    ),
    # facturas
    path(
        "facturas/list/",
        ClientesFacturaTemplateView.as_view(),
        name="clientes_facturas_list",
    ),
    path(
        "facturas/detail/<int:pk>/",
        ClientesFacturaDetailView.as_view(),
        name="clientes_factura_detail",
    ),
    path(
        "facturas/create/<int:investigacion_id>/",
        InvestigacionFacturaClienteArchivoCreateView.as_view(),
        name="clientes_factura_create",
    ),
    path(
        "facturas/create/<int:investigacion_id>/<int:pk>/",
        InvestigacionFacturaClienteArchivoUpdateView.as_view(),
        name="clientes_factura_update",
    ),
    path(
        "municipios/<str:efe_key>/",
        MunicipiosView.as_view(),
        name="clientes_municipios",
    ),
    # CANDIDATOS
    path(
        "candidatos/",
        CandidatosTemplateView.as_view(),
        name="candidatos_investigacion_list",
    ),
    path(
        "candidatos/empresa",
        CandidatosEmpresaTemplateView.as_view(),
        name="candidatos_investigacion_list",
    ),
]

project/project/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.conf import settings

from app.core.views.dash import DashboardView

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    
    url(r'^', include('app.front.urls')),

    url(r'^api/', include('app.api.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

    path("dash", DashboardView.as_view(), name="dashboard"),
    path("core/", include("app.core.urls")),
    path("clientes/", include("app.clientes.urls")),
    path("personas/", include("app.persona.urls")),
    path("investigaciones/", include("app.investigacion.urls")),
]


if settings.SHOW_DJANGO_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    SHOW_TOOLBAR_CALLBACK = True

project/app/clientes/forms.py
from allauth.account.forms import SignupForm
from django import forms as form2
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

project/app/clientes/views.py
# -*- coding: utf-8 -*-
from operator import inv
from braces.views import GroupRequiredMixin, LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.models import Group
from django.db.models import Sum
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)

from app.clientes.models import Cliente, ClienteSolicitud, ClienteSolicitudCandidato, ClienteUser
from app.core.models import Estado, Municipio
from django.http import HttpResponse
import json
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy

from app.persona.models import Persona
from app.investigacion.models import Investigacion
from datetime import date


class InitialClient(LoginRequiredMixin, TemplateView):

    template_name = 'clientes/initial_test.html'

    def get_context_data(self, **kwargs):
        context = super(InitialClient, self).get_context_data(**kwargs)
        context['title'] = 'Clientes'

        return context


class ClienteSolicitudListView(GroupRequiredMixin, ListView):

    # required
    group_required = [u"Admin", u"SuperAdmin"]
    raise_exception = True

    model = ClienteSolicitud
    paginate_by = 25

    context_object_name = "cliente_solicitudes"
    template_name = 'clientes/solicitudes/solicitudes_list.html'

    page = {
        'title': 'Solicitudes',
    }

    def get_context_data(self, **kwargs):
        context = super(ClienteSolicitudListView, self).get_context_data(**kwargs)

        context['page'] = self.page
        u = User.objects.get(id=self.request.user.pk)

        cliente_user = None
        try:
            cliente_user =  ClienteUser.objects.get(username=u.username)
        except ClienteUser.DoesNotExist:
            print('Error en cliente_user')
        
        context['uc'] = cliente_user

        return context


class ClienteSolicitudCreateTemplateView(GroupRequiredMixin, TemplateView):

    # required
    group_required = [u"Client",]
    raise_exception = True

    template_name = ''

    page = {
        'title': 'Projects',
    }

    def get(self, request, **kwargs):
        # cliente = Cliente.objects.get(user=request.user)
        u = User.objects.get(id=self.request.user.pk)
        cliente = ClienteUser.objects.get(username=u.username)
        solicitud = ClienteSolicitud()
        solicitud.cliente = cliente
        solicitud.save()
        return redirect('clientes:clientes_solicitud_detail', pk=solicitud.pk, **kwargs)


class ClienteSolicitudDetailView(GroupRequiredMixin, DetailView):

    # required
    group_required = [u"Client", u"SuperAdmin"]
    raise_exception = True

    model = ClienteSolicitud
    context_object_name = "cliente_solicitud"
    template_name = 'clientes/solicitudes/solicitud_detail.html'

    page = {
        'title': 'Detalle de Solicitud',
    }

    def get_context_data(self, **kwargs):
        context = super(ClienteSolicitudDetailView, self).get_context_data(**kwargs)

        context['page'] = self.page
        context['cliente_solicitud_candidatos'] = ClienteSolicitudCandidato.objects.filter(cliente_solicitud_id=self.object.pk)
        

        return context


class ClienteSolicitudEnviarTemplateView(GroupRequiredMixin, TemplateView):

    # required
    group_required = [u"Client",]
    raise_exception = True

    template_name = ''

    page = {
        'title': 'Projects',
    }

    def get(self, request, **kwargs):
       
        solicitud = ClienteSolicitud.objects.get(pk=self.kwargs['solicitud_id'])
        candidatos_solicitud = ClienteSolicitudCandidato.objects.filter(cliente_solicitud_id=self.kwargs['solicitud_id'])
        today = date.today()

        # Tipo de investigaciones 
        # Laboral, 
        # Visita Domiciliaria (Enrevista), 
        # Psicometrica
        # Validacion de Demanda,
        # 
        # En Conjunto:
        # Socio económina= Laboral + Visita Domiciliaria
        # Visita Domiciliaria con demanda
        # Ojo: Todos tienen demanda


        # Asocuación de campos

        # Listado de candidato de la solicitud.
        # en Listado de candidatos tener estado por cada servico asociado
        '''
        De investiacacion

        agente  (Para el coordinador)
        solicitud = ClienteSolicitud
        candidato = Persona
        compania = Compania
        sucursal = Sucursales
        contacto = Contacto, on_delete=models.CASCADE
        fecha_recibido = DateField
        hora_recibido = CharField
        puesto = models.CharField(max_length=140)

        tipo_investigacion_status
        '''

        for candidato in candidatos_solicitud:

            
            # Buscar Candidato si no existe crearlo
            try:
                persona = Persona.objects.get(nss=candidato.nss, curp=candidato.curp)
                persona.estado_id = candidato.estado_id
                persona.municipio_id = candidato.municipio_id
                # persona.save()
            except Persona.DoesNotExist:
                persona = Persona()
                persona.nss = candidato.nss
                persona.nombre = candidato.nombre
                persona.apellido = candidato.apellido
                persona.email = candidato.email
                persona.curp = candidato.curp
                persona.estado_id = candidato.estado_id
                persona.municipio_id = candidato.municipio_id
                persona.save()
                print('##### Persona creada #####')
                print('Persona creada', persona.pk)
                

            if candidato.tipo_investigacion == 2:
                print('Crear solicitud para candidato')

                investigacion = Investigacion()
                #investigacion.agente = solicitud.cliente.user
                investigacion.cliente_solicitud = solicitud
                investigacion.candidato = persona
                investigacion.compania = solicitud.cliente.compania
                investigacion.tipo_investigacion_status = candidato.tipo_investigacion
                # Colocar fehca y hora de envio por parte del cliente
                # compania sucursa y contacto tomarlo de la compachia del cliente
                # colocar en el formulario del cliente la sucursal
                # investigacion.sucursal = solicitud.cliente.compania.sucursal
                # investigacion.contacto = candidato.cliente.contacto
                investigacion.save()
                print('##############################')
                print('Investigacion creada con el id: ' + str(investigacion.pk))

                # crear entrevista + adjuntos
                # Crear laboral
                # Enviar notificacion a cliente y coordinador de ejecutivos
                # Coordinador de ejecutivos puede listar las solicitudes para asignarlas
                # Ejecutivo puede asignar una solicitud a un ejecutivo
                # Ejecutivo puede ver las solicitudes asignadas
                # Ejecutivo puede ejectuta solicitud
                # Ejecutivo termina solicitud
                # Colocar el costo al tipo de investigacion (Referencia)

                # adicionales
                # Puede editar la informacion del candidato el coordinador y ejecutivo de inv. laboral
                # hasta DOMICILIO ACTUAL (Trabajo del ejecutivo, a traves de llamada con el candidato)
                # Guardar la bitacora de llamadas
                # Al estar lleno los datos se activa la invistigacion.
                # 
                # Demandas laborales el coordinador las llena. Toda investigacion lleva demana 

                # Quien auoriza la Entrevista
                # Enviado a entrevistador eliminar y colocar el gestor con popup de usuarios gestores
                # Colocar bitacora
                # Estatus: Atención y concluida

                # Calificación Final cuando todos los procesos estan concluido

                # Investigacion laboral la ejeuta el ejecutivo de inv. laboral
            
            if candidato.tipo_investigacion == 4:
                print('Crear psicometria para candidato')
                # Genera la sicometria
                # Coordinador de ejecutivos las asigna a un ejecutivo
                # Ejecutivo puede listar las sicometrias para asignarlas
                # Enviar notificacion a Ejecutico y coordinador de ejecutivos
                # Ejecutivo termina la sicometria
                # ejecutivo recibe notificacion de terminacion de sicometria

        # Para ir eliminando
        # Persona creada 26014
        # 
        # Crear solicitud para candidato
        # ##############################
        # Investigacion creada con el id: 25991
        # Crear solicitud para candidato
        # ##############################
        # Investigacion creada con el id: 25992    
        
        # cambiar la solicitud a enviada
        solicitud.enviado = True
        solicitud.save()
        messages.add_message(self.request, messages.SUCCESS, 'El solicitud ha sido enviada satisfactoriamente.')
        return redirect('clientes:clientes_solicitud_detail', pk=solicitud.pk,)


class ClienteSolicitudDeleteView(GroupRequiredMixin, DeleteView):

    # required
    group_required = [u"Admin", u"SuperAdmin"]
    raise_exception = True

    model = ClienteSolicitud
    template_name = 'clientes/solicitudes/solicitud_confirm_delete.html'
    success_url = reverse_lazy('clientes:clientes_solicitudes_list')

    page = {
        'title': 'Eliminar Solicitud',
        'subtitle': 'delete file'
    }

    def get_context_data(self, **kwargs):
        context = super(ClienteSolicitudDeleteView, self).get_context_data(**kwargs)
        context['page'] = self.page

        return context


class ClienteSolicitudCandidatoCreateView(GroupRequiredMixin, CreateView):

    # required

project/templates/clientes/solicitudes/solicitud_confirm_delete.html
{% extends 'partials/base.html' %}
{% load static i18n crispy_forms_tags %}



{% block content %}

<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">

  <div class="page-content">
    <div class="container-fluid">

      <!-- start page title -->
      <div class="row">
        <div class="col-12">
          <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">Eliminación de solicitude</h4>

            <div class="page-title-right">
              <ol class="breadcrumb m-0">
                <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                <li class="breadcrumb-item active">Listado de solicitudes</li>
                <li class="breadcrumb-item active">Eliminar</li>
              </ol>
            </div>

          </div>
        </div>
      </div>
      <!-- end page title -->

      <div class="row">

        <div class="col-xl-12">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Solicitud nro: {{object.pk}}</h4>
              <div class="row">
                <div class="col-lg-6">
                 
                </div>

                <div class="col-lg-6 text-end">
                 
                </div>
              </div>
            </div>
            <div class="card-body">

              <!-- start: FROM -->
              <form action="" method="post">{% csrf_token %}

                <table class="table table-bordered">

                  <tr>
                    <td><b>Fecha de solicitud:</b></td>
                    <td>
                         {{object.fecha_solicitud}} 
                    </td>
                  </tr>

                </table>

                <p>¿ Estas seguro de eliminar esta solicitud ?</p>

                <a href="" onclick="document.forms[0].submit();return false;"
                  class="btn btn-danger waves-effect btn-label waves-light"> <i class="bx bx-trash-alt label-icon"></i>
                  Eliminar</a>
                <a href="{% url 'clientes:clientes_solicitudes_list' %}"
                  class="btn btn-success waves-effect btn-label waves-light"> <i class="bx bx-arrow-back label-icon"></i>
                   Cancelar</a>


              </form>
              <!-- end: FROM -->

            </div>
          </div>
          <!-- end card body -->
        </div>
        <!-- end card -->
      </div>
      <!-- end col -->
    </div>
    <!-- end row -->



  </div>
  <!-- End Page-content -->
  {% block footer %}
  {% include 'partials/footer.html' %}
  {% endblock footer %}
</div>


{% endblock content %}

project/templates/clientes/solicitudes/solicitud_detail.html
{% extends 'partials/base.html' %}
{% load static  %}
{% block title %}Lisado de solicitudes | Contakcto{% endblock title %}

{% block content %}
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0 font-size-18">Detalle de solicitud</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                                <li class="breadcrumb-item active">Listado de solicitudes</li>
                                <li class="breadcrumb-item active">Detalle</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end page title -->


            <div class="row">

                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Solicitud nro: {{cliente_solicitud.pk}}</h4>
                            <div class="row">
                                <div class="col-lg-6">
                                    <p class="card-title-desc">
                                    Fecha de solicitud: {{cliente_solicitud.fecha_solicitud}} / Estatus: {{cliente_solicitud.enviado}}
                                    </p>
                                </div>

                                <div class="col-lg-6 text-end">
                                    
                                    {% if not cliente_solicitud.enviado %}
                                
                                    <a href="{% url 'clientes:clientes_solicitud_candidato_create' cliente_solicitud.pk %}"
                                    class="btn btn-primary waves-effect btn-label waves-light"> <i class="bx bx-plus label-icon"></i>Agregar candidato</a>
                                    
                                    <a href="{% url 'clientes:clientes_solicitud_enviar' cliente_solicitud.pk %}"
                                    class="btn btn-success waves-effect btn-label waves-light"> <i class="bx bx-check label-icon"></i>Enviar solicitud</a>  

                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="card-body">

                            {% if messages %}
                            {% for message in messages %}
                            <input type="hidden" id="login-msg" value="{{message}}">
                            <button type="button" class="btn btn-primary" id="borderedToast1Btn" hidden>Primary toast</button>
                            <div style="z-index: 11">
                                <div id="borderedToast1" class="toast overflow-hidden mt-3 position-absolute top-0 end-0" role="alert" aria-live="assertive" aria-atomic="true">
                                    <div class="align-items-center text-white bg-primary border-0">
                                        <div class="d-flex">
                                            <div class="toast-body">
                                                {{message}}
                                            </div>
                                            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            {% endif %}

                            <h4>Listado de candidatos</h4>
                            <div class="table-responsive">
                                <table class="table table-striped mb-0">

                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>NSS</th>
                                            <th>Email</th>
                                            <th>Tipo de investigación</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for candidato in cliente_solicitud_candidatos %}
                                        <tr>
                                            <td>{{ candidato.id }}</td>
                                            <td>{{ candidato.nombre }}</td>
                                            <td>{{ candidato.apellido }}</td>
                                            <td>{{ candidato.nss }}</td>
                                            <td>{{ candidato.email }}</td>
                                            <td>
                                                
                                                {% if candidato.tipo_investigacion == 1  %}
                                                Laboral
                                                {% endif %}
                                                    
                                                {% if candidato.tipo_investigacion == 2  %}
                                                Socioeconómico
                                                {% endif %} 

                                                {% if candidato.tipo_investigacion == 4  %}
                                                Psicometrías
                                                {% endif %}

                                                {% if candidato.tipo_investigacion == 5  %}
                                                Visita Domiciliaria
                                                {% endif %}

                                                {% if candidato.tipo_investigacion == 7  %}
                                                Visita Domiciliaria con demandas
                                                {% endif %}

                                                {% if candidato.tipo_investigacion == 6  %}
                                                Validación de Demandas
                                                {% endif %}
                                            
                                            </td>
                                            <td>

                                                {% if not cliente_solicitud.enviado %}
                                                <div class="d-flex flex-wrap gap-2">
                                                    <a href="{% url 'clientes:clientes_solicitud_candidato_update' cliente_solicitud.pk candidato.pk %}"
                                                    class="btn btn-primary waves-effect btn-label waves-light"> <i class="bx bxs-user-detail label-icon"></i> Editar</a>

                                                    <a href="{% url 'clientes:clientes_solicitud_candidato_delete' cliente_solicitud.pk candidato.pk  %}"
                                                    class="btn btn-danger waves-effect btn-label waves-light"><i class="bx bx-trash-alt label-icon"></i>Eliminar</a>    
                                                   
                                                </div>
                                                {% else %}
                                                Solicitud está en proceso
                                                {% endif %}
                                                
                                                   
                                            </td>
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan="4">Solicitud no tiene candidatos registrados</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>

                                <a href="{% url 'clientes:clientes_solicitudes_list' %}"
                                class="btn btn-primary waves-effect btn-label waves-light"><i class="bx bx-arrow-back label-icon"></i> Regresar al listado</a>    
                               

                            </div>
                        </div>
                        <!-- end card body -->
                    </div>
                    <!-- end card -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->


        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->
    {% block footer %}
    {% include 'partials/footer.html' %}
    {% endblock footer %}
</div>
<!-- end main content-->
{% endblock content %}


{% block extra_js %}
<script>
    var user_login = document.getElementById("login-msg"),
    toastTrigger = document.getElementById("borderedToast1Btn"),
    toastLive = document.getElementById("borderedToast1");
    user_login && (toastTrigger.addEventListener("click", function () {
    new bootstrap.Toast(toastLive).show()
    }), toastTrigger.click());
</script>
{% endblock extra_js %}